### PR TITLE
Update for IDEA 2018.2 compatibility

### PR DESCRIPTION
**Pull request by vlad-ro**

### CODE REVIEW

**Comment by Blacksmoke16** [comment]
Any update on this?

**Comment by johansmitsnl** [comment]
Nothing so far?

**Comment by Iainmon** [comment]
Does it work? Why wont the merge?!?

**Comment by vlad-ro** [comment]
Works for me, use it on a daily basis. However looks like the project is no longer maintained. :(

**Comment by johansmitsnl** [comment]
@vlad-ro can you make a release so others can use it to? Maybe in a different name?

**Comment by vlad-ro** [comment]
A new version of the plugin with support for 2018.2 onwards has been published: https://plugins.jetbrains.com/plugin/11232-crystal-language-support-updated-for-v2018-2-onwards
Thank you for the nudge @johansmitsnl!

**Comment by kingsleyh** [comment]
Great thanks

**Pull request merged**
