### PR TITLE
Enable support of all products

### PR DESCRIPTION
**Pull request by GauthierPLM**

### CODE REVIEW

**Comment by fubarhouse** [comment]
+1

**Comment by kingsleyh** [comment]
Thanks :)

**Comment by fubarhouse** [comment]
Agreed! :)

**Comment by kingsleyh** [comment]
I've been busy with other stuff - but hopefully get back to this soon - the current state is not very good - It has many performance and indexing issues - so not very useable.

**Comment by faustinoaq** [comment]
Hi, I just discovered this https://github.com/gtache/intellij-lsp

Looks like [scry features](https://github.com/crystal-lang-tools/scry#roadmap) can be used on intelijj-idea as well :tada:

**Pull request merged**
