### PR TITLE
Base for creating crystal projects

### PR DESCRIPTION
**Pull request by s5bug**
- [x] Create projects using the Create New Project wizard
- [x] Properly set src/ and spec/ directories
- [ ] Importing existing crystal projects
- [ ] Creating a new/augmenting the existing gitignore
- [ ] Custom SDK/Framework to handle shard.yml and dependencies

### CODE REVIEW

**Comment by s5bug** [comment]
The Gradle `buildPlugin` for this seems to be incompatible with the latest IntelliJ version, should I fix that here or provide a separate PR for that?

**Comment by vlad-ro** [comment]
@sorenbug IDEA 2018.2 has some issues with v1.2 of the plugin. To get it to work properly you need to resize crystal.svg icon to 16x16 size. Have a look at my PR https://github.com/crystal-lang-tools/intellij-crystal-lang/pull/5,  might be useful to get your changes working with 2018.2

**Comment by kingsleyh** [comment]
Can this be merged?

**Comment by s5bug** [comment]
Probably not. I haven't done work yet on fixing all of the issues that would lie in that code's current state in 2018.2. I also have not been using Crystal recently due to my focus on Scala Native doing much of the work I do better in my use case.

If anyone wants to pick this back up, it shouldn't be hard to. Leaving this open so maintainers can decide what to do.

**Pull request closed without merging**
